### ISSUE TITLE
Android Bug 'plugin.moonassimp' dlopen failed: cannot locate symbol

### ISSUE THREAD

**Issue by Leonid-Ganin** [ggcrunchy/solar2d-plugins#4]
**After the build on Android, the moonassimp plugin throws this error on all devices:**

error loading module 'plugin.moonassimp' from file '/data/app/com.ganin.ccode-1M2yt-9Pl9o0ib1fwdUpOw==/lib/x86/libplugin.moonassimp.so':
    	dlopen failed: cannot locate symbol "_ZNSt6__ndk112basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEED2Ev" referenced by "/data/app/com.ganin.ccode-1M2yt-9Pl9o0ib1fwdUpOw==/lib/x86/libplugin.moonassimp.so"...

**Comment by ggcrunchy** [comment]
Oops, I only saw this just last night.

If you remember, was this related to the "experimental build" mentioned on the forum? I'm hoping to revisit that in the near future and tidy up the plugins / samples along the way. I had the Android version working on my own device but maybe I hadn't uploaded the binaries, or there are device-specific issues.

Or did you build it yourself?

**Comment by Leonid-Ganin** [comment]
@ggcrunchy I used the provided sample, which worked fine on win32, but after building on android - when starting the game it crashes with an error, nothing experimental was used

**Comment by ggcrunchy** [comment]
Hmm, weird. That was quite a chore to build, but seemed to work when I tested.

I have a PR or two to submit and a few to merge, with any luck soon, and then I can probably get back to experimental. Tests #4 and #5 [here](https://github.com/ggcrunchy/solar2d-plugins/tree/master/engine_testing) (see the `Solar` directories) use an OBJ loader from [luapower](https://luapower.com/), but it's very finicky and I'd like to migrate to **moonassimp**, so maybe I can give it some love again in the near future. (You can try your luck with that code, of course.)

Are you trying to do anything interesting with it, by the way? 🙂

**Comment by Leonid-Ganin** [comment]
I am the developer of the largest designer for creating games directly on mobile devices, it is written on the corona, it can build apk and aab offline directly on phones, but users demand the ability to create 3D games, so I’m trying to somehow connect your tool with mine

**Comment by Leonid-Ganin** [comment]
@ggcrunchy When is a fix possible? Hello

**Comment by ggcrunchy** [comment]
Not sure. I haven't really had an opportunity to sit down with it again. (Sounds a lot like [this](https://github.com/android/ndk/issues/1731), though.)

I see "/lib/x86/libplugin.moonassimp.so" in the error... is it particular to x86 devices, or happening on any target?

**Comment by Leonid-Ganin** [comment]
This is typical for all architectures @ggcrunchy

**Comment by ggcrunchy** [comment]
This seems to be resolved now.

**Assimp** is a C++ library, that I was building in one step into several **libassimp.a** files.

**moonassimp** is a C library, that in a separate step brings in each target's library file.

Since there were no C++ files, `clang` was being invoked rather than `clang++` and not bringing in **libstdc++**.

Adding a little dummy C++ source file appears to have fixed it. Perhaps there's a more elegant way to do the same, but it's pretty harmless.
